[package]
name = "database"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
diesel.workspace = true
dotenvy.workspace = true
chrono.workspace = true
tracing.workspace = true

common = { path = "../common" }
